### ISSUE TITLE
Zero radius circles sometimes drawn as a line

### ISSUE THREAD

**Issue by elkins0** [CindyJS/CindyJS#139]
Example geometry:
```javascript
	geometry: [ 
		{ name: "A", type: "Free", pos: [ 4.0, 3.0, 1.0 ], color: [ 1.0, 0.0, 0.0 ], labeled: true }, 
		{ name: "C0", type: "CircleMr", color: [ 0.0, 0.0, 1.0 ], args: [ "A" ], radius: 0, size: 1, printname: "$C_{0}$" } ], 
```

**Comment by strobelm** [comment]
Hi,

yes it's a known problem, since the circle ops use conic by 5 which for
small radius circles yields a degenerate conic in the conic drawing
routine. I'll fix that asap.

On 12/08/2015 07:49 PM, Alexander Elkins wrote:
>
> Example geometry:
>
>     geometry: [ 
>         { name: "A", type: "Free", pos: [ 4.0, 3.0, 1.0 ], color: [ 1.0, 0.0, 0.0 ], labeled: true }, 
>         { name: "C0", type: "CircleMr", color: [ 0.0, 0.0, 1.0 ], args: [ "A" ], radius: 0, size: 1, printname: "$C_{0}$" } ], 
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CindyJS/CindyJS/issues/139>.
>


-- 
Michael Strobel, M.Sc.

Technische Universität München -- Zentrum Mathematik
Lehrstuhl für Geometrie und Visualisierung (M10)
Boltzmannstr. 3, 85747 Garching bei München 
https://www-m10.ma.tum.de/bin/view/Lehrstuhl/MichaelStrobel
