### ISSUE TITLE
Setting .xy to homogeneous coordinates

### ISSUE THREAD

**Issue by kranich** [CindyJS/CindyJS#169]
Cinderella supports `A.xy = [3, 2, 1]` whereas CindyJS does not.

**Comment by kranich** [comment]
@strobelm Bad boy, you have merged this although the build failed! ;-)

#171 should fix the build issue.

**Comment by strobelm** [comment]
I'm feeling nasty ;-). I merged the commit since i thought that some
time ago @gagern and i came to terms that we could ignore the line (for
reasons i don't remember - perhaps some old jshint version or something
like that).

I will look into it.

On 01/18/2016 05:07 PM, Stefan Kranich wrote:
>
> @strobelm <https://github.com/strobelm> Bad boy, you have merged this
> although the build failed! ;-)
>
> #171 <https://github.com/CindyJS/CindyJS/pull/171> should fix the
> build issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CindyJS/CindyJS/issues/169#issuecomment-172571851>.
>


-- 
Michael Strobel, M.Sc.

Technische Universität München -- Zentrum Mathematik
Lehrstuhl für Geometrie und Visualisierung (M10)
Boltzmannstr. 3, 85747 Garching bei München 
https://www-m10.ma.tum.de/bin/view/Lehrstuhl/MichaelStrobel

**Comment by gagern** [comment]
I'm kind of surprised *why* anyone would want to write `A.xy = [3, 2, 1]` as opposed to `A.homog = [3, 2, 1]`, but if Cinderella does it this way, that's justification enough.

**Comment by gagern** [comment]
For the sake of completeness: Cinderella appears to allow several (undocumented!) aliases for points. Should we start supporting any of these?

* `posx` → `x`
* `posy` → `y`
* `val`, `pos`, `coord` → `xy`

Internally `xy` and `homog` are different code paths, but due to various automatic conversions they appear to end up doing essentially the same thing.

**Comment by kranich** [comment]
>I'm kind of surprised why anyone would want to write A.xy = [3, 2, 1] as opposed to A.homog = [3, 2, 1], but if Cinderella does it this way, that's justification enough.

I observed this in a widget exported from Cinderella. I would probably also simply have used `.homog`. Because exported widgets should ideally work out of the box, it appears reasonable to support this odd possibility.
