### ISSUE TITLE
Restructuring plugins

### ISSUE THREAD

**Issue by kranich** [CindyJS/CindyJS#186]
We currently have three plugins, namely `cindy3d`, `cindygl`, and `katex`.

Their sources reside in [src/js/](https://github.com/CindyJS/CindyJS/tree/master/src/js/) and  [src/str/](https://github.com/CindyJS/CindyJS/tree/master/src/str/).

I think it would be cleaner to move plugins to a `plugins` directory at the root of the repository, with a subdirectory for every plugin.

This would also make it much easier to integrate plugins that are developed in a separate repository.

What do you think?

**Comment by gagern** [comment]
:+1:

Although we should also consider sharing files between plugins one way or another.

**Comment by montaga** [comment]
I am also appreciating this.
What is about the examples? I think they should remain in the standard examples folder, because they are more a showcase than a backbone of functionality.

Files in `cindygl` that were shared from `cindy3d` are:
-`src/js/cindy3d/Interface.js`
-`src/js/cindy3d/ShaderProgram.js` (here the two replacements `uniform1fv`->`gl.uniform1f` and `gl.uniform1iv` ->`gl.uniform1i` were done but I think it should be possible to use the original file and having a little modification in `src/js/cindygl/Renderer.js` instead.

**Comment by kranich** [comment]
>Although we should also consider sharing files between plugins one way or another.

@gagern It is of course always possible to refer to sources of another plugins in the build task. Or do you have a cleaner solution in mind?

**Comment by kranich** [comment]
>What is about the examples? I think they should remain in the standard examples folder, because they are more a showcase than a backbone of functionality.

I think the examples should reside under the subdirectory of the plugin so that the plugin can be maintained in a separate repository, if desired. Then I would create a soft link to this directory in the main examples directory.

**Comment by kranich** [comment]
>Files in cindygl that were shared from cindy3d are:
-src/js/cindy3d/Interface.js
-src/js/cindy3d/ShaderProgram.js (here the two replacements uniform1fv->gl.uniform1f and gl.uniform1iv ->gl.uniform1i were done but I think it should be possible to use the original file and having a little modification in src/js/cindygl/Renderer.js instead.

@montaga I will prepare a pull request for that.

**Comment by kranich** [comment]
@montaga Please have a look at [kranich/CindyJS/cgl_mods_from_c3d](https://github.com/kranich/CindyJS/tree/cgl_mods_from_c3d). If you agree, I will merge this into [kranich/CindyJS/plugins](https://github.com/kranich/CindyJS/tree/plugins), so it becomes part of this pull request.

**Comment by gagern** [comment]
> I think the examples should reside under the subdirectory of the plugin so that the plugin can be maintained in a separate repository, if desired. Then I would create a soft link to this directory in the main examples directory.

I know @richter-gebert in particular is opposed to symlinks. The rationale is that there is some danger that you'll copy stuff around, in particular to a non-symlink-enabled file system, and suddenly things stop to work. Symlinks also don't agree with #107. And as you found out in the comments on https://github.com/kranich/CindyJS/commit/5d1c0f1ab66999f507a75cf01369fae1ed68a2ce, it's sometimes difficult to get relative paths right in such a setup, because systems may have different ideas whether to resolve them relative to the location involving the symlink or to the target location the symlink actually points at.

So I think we have to decide whether to have the examples *either* in the plugin directory *or* in the top level examples directory.

The main **reason to move** the examples to the plugin directory is the possibility to move them to a separate repository. But I don't see us doing that any day soon, at least for these plugins here. Working with git submodules adds a lot of complexity, so we should avoid that here unless necessary. And the connection between plugin and core is pretty close, so they currently have to be developed in lockstep.

There are I think two **reasons to leave** the examples in the examples directory. One is discoverability: people can look at the examples directory and get a good idea of *all* the features. If we move the files, they may be missing the fact that these plugins even exist, and might not see what they can do. The other reason is deployment: currently copying `build/js` and `examples` will be enough to demonstrate all of the examples to an audience. This may in particular be important in some space-constrained setups. Copying parts of the `plugins` directory will make this workflow more difficult.

I think we should definitely get input from @richter-gebert on this.

**Comment by kranich** [comment]
>The main reason to move the examples to the plugin directory is the possibility to move them to a separate repository. But I don't see us doing that any day soon, at least for these plugins here. Working with git submodules adds a lot of complexity, so we should avoid that here unless necessary. And the connection between plugin and core is pretty close, so they currently have to be developed in lockstep.

Agreed. My main motivation for restructuring is that I will develop a plugin in a separate repository. Its integration with CindyJS is not as close as with `cindy3d` and `cindygl`. (It also works independently of CindyJS.)
Having the plugin in a separate folder makes updates (by `git read-tree` or manual copying) much easier.

Even if the examples in the plugin directory we part of a separate repository, they would not work in the separate repository without changing paths. One more reason not to move the examples.

I have modified the pull request to leave the examples untouched for the time being.

**Comment by montaga** [comment]
> @montaga Please have a look at kranich/CindyJS/cgl_mods_from_c3d. If you agree, I will merge this into kranich/CindyJS/plugins, so it becomes part of pull request #191.

kranich/CindyJS/cgl_mods_from_c3d looks nice. Thank you for the changes in `Renderer.js`

**Comment by kranich** [comment]
>kranich/CindyJS/cgl_mods_from_c3d looks nice.

OK, I just updated pull request #191.

>Thank you for the changes in `Renderer.js`

You're welcome.
