### ISSUE TITLE
Point names

### ISSUE THREAD

**Issue by kranich** [CindyJS/CindyJS#215]
Cinderella 'reserves' point names `I` and `J` for the circular points. In a construction with 9 points (e.g. Pappus' theorem), the points are automatically named `A`, `B`, `C`, `D`, `E`, `F`, `G`, `H`, `K`.

CindyJS does not care about this convention so far. The 9th point in [examples/20_Pappos.html](https://github.com/CindyJS/CindyJS/blob/master/examples/20_Pappos.html) is named `I`. Clearly, this example has been handwritten and it is also possible to change the name to `I` in Cinderella's inspector.

Do we want to stick to Cinderella's convention?

**Comment by gagern** [comment]
I'm not sure whether `I` and `J` were reserved for the ideal circle point, which are not defined automatically either. It might be just following a convention to not use `I` and `J` since they can easily be confused in some fonts and handwritings. Perhaps it's both reasons taken together.

In my opinion, this is only relevant when *adding* new points. So when the createtool branch becomes ready for merging, we might consider such things there. I guess I'd stick with compatibility, perhaps with a way to configure this behavior. If we want to do full Cinderella compatibility in this respect, then we'd use a completely different set of point names if the language is configured to Japanese.

I don't see an urgent need to change existing examples to match that convention, although I wouldn't have a problem with it either if someone feels more strongly about this and submits a pull request.

**Comment by kortenkamp** [comment]
@gagern is right: we just avoid I and J when automatically naming points, in order to avoid confusion of any kind.

btw: Japanese does not use different conventions for naming points, as I learned that this is not common.

**Comment by kranich** [comment]
@gagern @kortenkamp OK.
