### ISSUE TITLE
CindyGL and nested if

### ISSUE THREAD

**Issue by kranich** [CindyJS/CindyJS#245]
CindyGL seems to have problems with nested if statements.

When I tried to implement my own hue function

```
hueToRGB(hue) := (
    hue = mod(hue / pi * 180, 360) / 60;
    h = floor(hue);
    f = hue - h;
    if(h == 0,
        [1,f,0]
    , if(h == 1,
        [1-f,1,0]
    , if(h == 2,
        [0,1,f]
    , if(h == 3,
        [0,1-f,1],
    , if(h == 4,
        [f,0,1],
    , if(h == 5,
        [1,0,1-f]
    ))))));
);
```

the following errors were thrown:

```
float[3] is no subtype of voidt (trying to cast the term vec3(float(1),float(0),(float(1)-f))) CindyGL.js:23:595

Could not find a signature for if(bool, float[3], voidt, voidt).
Returning empty code CindyGL.js:34:33

Could not find a signature for if(bool, float[3], voidt, voidt).
Returning empty code CindyGL.js:34:33

voidt is no subtype of float[3] (trying to cast the term )
```

The following workaround did not throw any errors:

```
hueToRGB(hue) := (
    hue = mod(hue / pi * 180, 360) / 60;
    h = floor(hue);
    f = hue - h;
    col = [1,f,0];
    if(h == 1, col = [1-f,1,0]);
    if(h == 2, col = [0,1,f]);
    if(h == 3, col = [0,1-f,1]);
    if(h == 4, col = [f,0,1]);
    if(h == 5, col = [1,0,1-f]);
    col;
);
```

Originally, I wanted to write

```
hueToRGB(hue) := (
    regional(h, f);
    hue = mod(hue / pi * 180, 360) / 60;
    h = floor(hue);
    f = hue - h;
    [[1,f,0],[1-f,1,0],[0,1,f],[0,1-f,1],[f,0,1],[1,0,1-f]]_(h+1);
);
```

but this did not work due to #243 and #244.

**Comment by montaga** [comment]
@kranich, thank you for your detailed bug report.
Your last if did not have any else branch and CindyGL does not know which type it should assert here. If we change your Code to
```
      if(h == 0,
        [1,f,0]
    , if(h == 1,
        [1-f,1,0]
    , if(h == 2,
        [0,1,f]
    , if(h == 3,
        [0,1-f,1] //no , here
    , if(h == 4,
        [f,0,1] //no , here
    , if(h == 5,
        [1,0,1-f]
    , [0,0,0] //default value
    ))))));
```
or even better to
```
      if(h == 0,
        [1,f,0]
    , if(h == 1,
        [1-f,1,0]
    , if(h == 2,
        [0,1,f]
    , if(h == 3,
        [0,1-f,1] //no , here
    , if(h == 4,
        [f,0,1] //no , here
    ,   [1,0,1-f]
    )))));
```
it works. But yes, this it not really clear from the errors that were thrown.

One question that arises from that issue is, how we should handle the value of if(<bool>,<expr>) (i.e. if-clauses without else-branch). Maybe we should simply return some default value which has the same type as expression?

I agree that
`    [[1,f,0],[1-f,1,0],[0,1,f],[0,1-f,1],[f,0,1],[1,0,1-f]]_(h+1);` was indeed very nice. I am not sure whether something like this could ever by poured into GLSL as the compiler cannot prove that there is no Array Index Out Of Bounds Exception.

**Comment by kranich** [comment]
>One question that arises from that issue is, how we should handle the value of if(<bool>,<expr>) (i.e. if-clauses without else-branch) if the boolean expression is not fulfilled. Maybe we should simply return some default value which has the same type as the value-expression?

I agree.

>I agree that
[[1,f,0],[1-f,1,0],[0,1,f],[0,1-f,1],[f,0,1],[1,0,1-f]]_(h+1); was indeed very nice. I am not sure whether something like this could ever by poured into GLSL as the compiler cannot prove that there is no Array Index Out Of Bounds Exception.

You are absolutely right, this first attempt was too naive and probably cannot be translated into GLSL so easily.
