### ISSUE TITLE
Incorrect results in Lie circle geometry computation

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#258]
In [this example](http://martin.von-gagern.net/se/MX1657718) I've used Lie circle geometry to sole an instance of Apollonius' problem. In Cinderella this works nicely: the cyan circles touch the blue circle and two of the lines. In CindyJS, however, the result looks just wrong.

I haven't found time yet to investigate this problem and see where the implementations diverge. So right now this ticket here is mostly a reminder to do some further investigation. If I find the actual cause, I might edit it with a more detailed description of what's actually going on.

**Comment by strobelm** [comment]
On 02/17/2016 12:07 AM, Martin von Gagern wrote:
>
> In this example <http://martin.von-gagern.net/se/MX1657718> I've used
> Lie circle geometry to sole an instance of Apollonius' problem. In
> Cinderella this works nicely: the cyan circles touch the blue circle
> and two of the lines. In CindyJS, however, the result looks just wrong.
>
> I haven't found time yet to investigate this problem and see where the
> implementations diverge. So right now this ticket here is mostly a
> reminder to do some further investigation. If I find the actual cause,
> I might edit it with a more detailed description of what's actually
> going on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CindyJS/CindyJS/issues/258>.
>

You are refereeing to the jumping circles, aren't you? Additionally
there are drawing bugs caused by canvas.arc, i think we want to use the
conic drawing routine (although it's expensive) since it's doing the
drawing at least not as bad as canvas.arc. The Bezier curves which
@richter proposed cause problems rendering infinite radii (at least what
i can tell here).

-- 
Michael Strobel, M.Sc.

Technische Universität München -- Zentrum Mathematik
Lehrstuhl für Geometrie und Visualisierung (M10)
Boltzmannstr. 3, 85747 Garching bei München 
https://www-m10.ma.tum.de/bin/view/Lehrstuhl/MichaelStrobel

**Comment by gagern** [comment]
@kranich: I'm referring mainly to the fact that the circles are not tangent to the other things, but the jumping probably is a consequence thereof. I'll have the script print out the raw circle drawing data, in case it's just rendering bugs, but I doubt it.
