### ISSUE TITLE
Number.isFinite not supported old versions of Safari

### ISSUE THREAD

**Issue by montaga** [CindyJS/CindyJS#338]
When trying CindyJS I noticed that it does not work anymore on the old M10-Macbook. The reason for that is that Number.isFinite is used, which is not supported by Safari (<9).
According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite it is not supported by IE at all.
Instead we could use isFinite.

**Comment by gagern** [comment]
We should be careful, since there may be slight differences in semantics. `Number.isFinite(x)` is equivalent to `typeof x === 'number' && isFinite(x)`.

The `grid` properties in `Setup.js` use `Number.isFinite`. They calls might indeed be meant as type checks in addition to finiteness checks. These are the only occurrences of `Number.isFinite` that I can see.

These are the occurrences of the unqualified global `isFinite`function that I could see:

1. `CSNumber._helper.isFinite` is implemented in terms of `isFinite`. The argument is assumed to be `ctype:"number"` so this makes sense.
1. `Timer.js` is using `isFinite` for its own internal variable `delay` which presumably will always be numeric.
1. CindyGL uses `isFinite` in its `setpixel` implementation, after coercion to integers.
1. CindyGL also uses `isFinite` in `accessbyshiftedindex`. I'm not sure about the intention there, so please check this one yourself.
