### ISSUE TITLE
make alltests fails due to deployment

### ISSUE THREAD

**Issue by strobelm** [CindyJS/CindyJS#43]
Hi!
Something is wrong with our deployment, at least make alltests says so:

```
node tools/prepare-deploy.js

/mnt/data/Dokumente/promotion/cindyjs/tools/prepare-deploy.js:82
        return ppath.normalize(ppath.join("build/js", root, src));
                                     ^
TypeError: Cannot call method 'join' of undefined
    at /mnt/data/Dokumente/promotion/cindyjs/tools/prepare-deploy.js:82:38
    at Array.map (native)
    at map (/mnt/data/Dokumente/promotion/cindyjs/tools/prepare-deploy.js:81:31)
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
Makefile:355: recipe for target 'deploy' failed
make: *** [deploy] Error 8
```

**Comment by gagern** [comment]
This is strange, since in https://travis-ci.org/CindyJS/CindyJS/builds/87445447 the `prepare-deploy.js` script ran without such issues. Probably due to the version of node being used here, so what are you using? `ppath` is defined as `path.posix` so theoretically this code should be in node since nodejs/node@6a90a060023dac4fc827613243e496237403f29f first released in node.js 0.11.15. Since our Makefile downloads 0.12.6 if no preinstalled version of node can be found, I'd guess you have some ancient node on your system. Could this be the case?

**Comment by strobelm** [comment]
You found the culprit, my Fedora package management delivers version 0.10.36. Well bleeding edge isn't as bloodily as i used to be.

**Comment by gagern** [comment]
There is quite a gap between 0.10 and bleeding edge. Perhaps we should introduce some kind of machinery to identify inadequate versions of all the things we *can* download but won't download if they already exist. Haven't worked out how to programmatically check the node version, though.

**Comment by gagern** [comment]
Found it: [`process.version`](https://nodejs.org/api/process.html#process_process_version)

**Comment by strobelm** [comment]
It feels really strange that fedora deploys quite an outdated version here, but Fedora 23 is around the corner.
