### ISSUE TITLE
dropping numeric.js

### ISSUE THREAD

**Issue by strobelm** [CindyJS/CindyJS#45]
Hi! I had a look into our linear algebra routines and noticed that numeric.js is hardly used in our algorithms anymore. The only real usage is currently in the conic drawing routine where i rotate the conic for some reasons, which is only a 3x3 matrix multiplication. I could easily patch the code in order to use List.*. 

Furthermore there are List.inversereal, List.linearsolvereal and List.detreal which aren't used in productive code at all (as far i can see).

Therefor is there any reason to keep numeric.js? The benefit would be a 10% saving in the current Cindy.js filesize (minimized version).

**Comment by gagern** [comment]
I'm very much in favor of dropping numeric.js.

As described in https://github.com/sloisel/numeric/pull/63, numeric.js depends on polluting the global namespace, which might have adverse effects if CindyJS gets combined with other pieces of code, in particular if that code employs other versions of numeric.js.

Another point is that [the upstream master](https://github.com/sloisel/numeric/commits/master) hasn't seen any activity since 2012, despite [some open issues](https://github.com/sloisel/numeric/issues?utf8=%E2%9C%93&q=is%3Aopen+). There are [various more recently active branches](https://github.com/sloisel/numeric/network) by different people, but none of them seems to have established itself as the new “official” fork of the project.

I hadn't realized we were this close to actually removing that dependency. If you think it can be done with reasonable effort, I'd say go ahead and prepare a pull request. :+1:
