### ISSUE TITLE
make deploy fails if cindyjs is not obtained via git

### ISSUE THREAD

**Issue by strobelm** [CindyJS/CindyJS#520]
If someone doesn't clone cindyjs (e.g. used the github zip download function) make deploy fails complaining about not being a git repository.

**Comment by gagern** [comment]
This is intentional.

One part of the deployment process is [the insertion of the git commit id](https://github.com/CindyJS/CindyJS/blob/v0.8.1/tools/prepare-deploy.js#L86) into the generated files. You can't do that from a zip file. For most applications, the build directory can serve as a substitute. If you have some specific use case in mind where being able to deploy from zip would be desirable, then we can discuss it and see what to do about those git ids in that case.

Another thing worth considering is the version as returned by [the `version()` cindyscript function](https://github.com/CindyJS/CindyJS/blob/v0.8.1/src/js/libcs/Operators.js#L5-L8). It too relies on git, and although [we do have fallback code for this](https://github.com/CindyJS/CindyJS/blob/v0.8.1/make/getversion.js#L34-L38), having a version with this fallback deployed to a wider audience is in my opinion undesirable, since it may break widgets which rely on this versioning.

**Comment by strobelm** [comment]
Alright, thanks for the explanation.
