### ISSUE TITLE
Continuity does not work 

### ISSUE THREAD

**Issue by montaga** [CindyJS/CindyJS#539]
In the attached file CindyJS handles the continuity while moving the point Y different than Cinderella: In CindyJS, it seems to be impossible to switch sides after making X Y P being co-linear. In Cinderella we can always switch the sides.
![screenshot](https://cloud.githubusercontent.com/assets/15124152/20563140/77b9bb56-b187-11e6-9884-bc48230f0c1b.png)

[Papierstreifen.zip](https://github.com/CindyJS/CindyJS/files/608883/Papierstreifen.zip)

**Comment by gagern** [comment]
I hope you'll edit in a textual description…

**Comment by gagern** [comment]
Strange! I don't know how Cinderella does this. I'd have assumed that this kind of interaction between Script and geometric construction would break all tracing.

I tried creating a version which does not depend on a script, and found that it will always stay in one half of the configuration space. See [this ZIP file](https://github.com/CindyJS/CindyJS/files/609074/Papierstreifen2.zip) if you want a look. I guess this might be due to the fact that we never *exactly*  reach the end of the segment during tracing, and thus literally can't get into the other half. Which is a pity. I wonder whether we can change anything about point on segment to make this work. But I guess here we should stick to the main question of how to get your scripted version to work.

**Comment by kortenkamp** [comment]
Well, in Cinderella we do not stop in reality, but move into complex space (and back), IIRC. So the switch is for sure.

Scripting should not break tracing, by the way (sometimes it does, though).

**Comment by gagern** [comment]
> Scripting should not break tracing, by the way (sometimes it does, though).

Scripting itself should not break tracing. But changing the mover does, right? And a script which changes the position of a point does change the mover. Hmmm… Except if the point it's changing is the one that's being moved by mouse, too. Perhaps this has something to do with the fact that Cinderella detects a change of mover when the second object starts moving, while CindyJS already assumes a change of mover if you lift the mouse button while moving, so that moving the same object again later on will start from the singular situation.

> Well, in Cinderella we do not stop in reality, but move into complex space (and back), IIRC. So the switch is for sure.

*What* does not stop in reality, but move through complex space? What you describe makes sense for animations, where the animation control has the option to continue moving objects after some dependent objects became complex, and then move back until they become real again. But although the visual effect is very similar here, I don't see how that logic could affect the control flow here, as the point in question is not under animation control, but moved by the user and restricted by some script.

Hmmm… Perhaps the point does move past the restriction, leading to complex results, and then gets moved back by the script, thus resulting in the same kind of movement as we see for animations.

I suggest we try to make CindyJS be more flexible with different movements of the same mover. So that a single mover moved in turns by different mouse drags and some script will still amount to one single traceable move operation. That might fix the issue at hand, and is something we should be doing anyway. I'll look into this.

**Comment by gagern** [comment]
I've got a bit of code to defer switching between movers, as indicated above. And it does indeed seem to solve the issue at hand, at least most of the time. However, I'm no longer sure why it does so. The script does move different points (*D* and *Y*), contrary to what I had assumed at first. I'd like to investigate this further, to see what's actually happening here.

While trying to write a simple demonstration of this situation, I found that I has mispredicted how CIndyJS would behave. I intersected a circle with a line, and had the center of the circle restricted by the script. The result was that the point of intersection *never* switched sides. That's because although the mouse move ended at a non-singular position with complex coordinates, the script then returned from there to a singular situation. And [the check whether the position is non-singular](https://github.com/CindyJS/CindyJS/blob/v0.8.2/src/js/libgeo/Tracing.js#L99-L114) takes both the mouse move *and* the scripts into account, combining them into a single move. Which makes sense, in my opinion, but which also means that the motivation I assumed above for how the switching of sides might work doesn't apply to this model.

In Cinderella, my toy example *does* cause a switching of sides. So I would assume that Cinderella does checkpoint the non-singular position after the mouse move but before the execution of the scripts. Is this something we want for CindyJS as well, either for the sake of compatibility, or because there is some mathematical reason why that approach is more correct than combining the mouse move and the script execution into a single operation which either completely succeeds or completely fails?

**Comment by gagern** [comment]
This is how I recreated the example in question to make it work with the current codebase from #544: [Papierstreifen4.zip](https://github.com/CindyJS/CindyJS/files/619828/Papierstreifen4.zip). The ZIP contains a folder `Papierstreifen` which should go into the `private_examples` directory or similar since it references CindyJS using `../../build/js/Cindy.js`. It makes use of the new function `continue from here()` I introduced there.

I've simplified the construction somewhat: instead of constructing a conic through five points I used the ConicFromPrincipalDirections algorithm which uses three points only. This has the benefit that I don't have to set the position of *D* from the script, which is important as setting said position would cause an assignment to some position other than *Y*, while conditionally setting it would complicate the script.

On the other hand, I moved the drawing of the offset segment *XP* from the script to the construction. The radius of the invisible circle *C4* controls the offset distance. That removes the draw call from the script, so the script code can concentrate on the important part here.

Do you think I should include this as a second example for #544?

**Comment by montaga** [comment]
Thank you @gagern for making this example work. I have included this example in #544
