### ISSUE TITLE
Deprecate support of node 0.12

### ISSUE THREAD

**Issue by kranich** [CindyJS/CindyJS#615]
Is there any reason why we still use node 0.12 in our Travis CI builds? This causes some problems with using gulp for building the Complex Curves plugin. (Some dependencies of gulp require node >= 4.0.0.)

See #614.

**Comment by kranich** [comment]
Maybe @gagern can shed light on this?

**Comment by gagern** [comment]
No real reason, except that 0.12 was still very much around when I started this. Feel free to update once all core developers are happy using a newer version. This might mean the latest package on whatever linux distributions are in use. Ubuntu is on node 4 since xenial, so I would suggest using node 4 as earliest version for Travis runs, but perhaps auto-installing node 8 if no recent enough version of node is detected. That way we should be able to avoid unneccessary updates for developers using the auto-download feature. Ideally [travis](https://github.com/CindyJS/CindyJS/blob/dc328451d39ca3175ff750c6a683921008575668/.travis.yml#L4) and [makefile](https://github.com/CindyJS/CindyJS/blob/dc328451d39ca3175ff750c6a683921008575668/Makefile#L27) should be the only source locations needing changes. Auto-install in particular might require additional work, though.

One thing that I'm slightly worried about is the fact that node 4 supports many es6 features that node 0.12 did not. So we might end up in a situation where we start using stuff that is only available in es6 without even noticing it. Not sure how to guard against this. For syntax closure should isolate us sufficiently well, but for runtime libraries this might well cause issues. I guess we just have to be careful.

**Comment by kranich** [comment]
I don't see how using node 4 changes any risk of inadvertently using es6 features in our code base. Our sources are transpiled using Closure Compiler. If anything, using node 4 enables us to use es6 features in our build system. (This is what gulp does and why it fails with node <4.) But isn't this a good thing?

Put differently, even with the status quo, we are at risk of using es6 runtime features (e.g. promises) that are not transpired by Closure Compiler and for which we needed to use a polyfill. Using node 4 for the build system does not change that in any way.

Or am I missing something?

**Comment by kranich** [comment]
Can @richter-gebert, @kortenkamp, @strobelm, and/or @montaga please comment on this?

**Comment by kortenkamp** [comment]
I couldn't care less… just go ahead, as long as I am still able to have a development environment on my Mac.

**Comment by kranich** [comment]
Inhowfar is this related to #562?

**Comment by montaga** [comment]
https://github.com/CindyJS/CindyJS/pull/614 runs out of the box for our testing MacBook air.
I agree with @kranich that we do not loose anything with using node 4.
