### ISSUE TITLE
KaTeX cannot handle color in TeX

### ISSUE THREAD

**Issue by kortenkamp** [CindyJS/CindyJS#704]
As visible in http://cinderella.de/files/VereinigungSchnittDifferenz.cdy.html KaTeX does have problems with color commands in TeX, which Cinderella can handle quite well.

**Comment by montaga** [comment]
The problem reduces to the fact that `geoElement.label` is not implemented. If `#.label` is replaced by `#.name`, then the TeX colors in your example seems to work.

A further problem is that $\not\in$ is not rendered. However, $\notin$ renders well. Since this works fine on https://katex.org/, maybe this is an issue with loading a too old version of KaTeX.

**Comment by kortenkamp** [comment]
Great, thank you for the analysis and the workaround. I admit I did not go through the details…
