### ISSUE TITLE
How to embed CindyJS only with a file (similar to a javascript file)?

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#733]
It would be great to be able to have the cindyjs code embedded only with one file.

But I am not sure if that works because CindyJS is using those custom CS* script tags.

My goal would be an embed like:

     <script src="mysite.com/myscripts/cindyjs/rectangle/script.01.js"></script>

which holds all the necessary cindy script.

How is that possible?

**Comment by montaga** [comment]
An partial answer can be found at [in the reference](https://cindyjs.org/ref/createCindy.html#scripts).

When `CindyJS` is created, instead of specifying something like `scripts: "cs*",` , it is also possible to specify a JavaScript Object containing all scripts as string. As in [the attachment](https://github.com/CindyJS/CindyJS/files/2754357/onefile.zip), you can build an external file that holds all the cindy script.

When you specify the code within javascript, it might be a bit cumbersome to create multiple line strings. If you do not care about compatibility with IE, I would use [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) in order to specify multi-line code there.

**Comment by montaga** [comment]
Now you would mix javascript and cindyscript, which is not possible directly.

For your approach, all the cindscipt code has to be specified as a string within javascript. We introduced these separate <script>-blogs to have a nice way to define these strings containing cindyscript and to have a proper separation.

In your example, you could define 
```
scripts: {
        init: `resetclock();
               drawmystage():= ( //this is the way a function is defined in CindyScript
                    //do some fancy drawing stuff...
                    draw((0,0),(cos(seconds()),sin(seconds()));
               );
        `,
        draw: `drawmystage();`
    },
```
or you could for instance start from an object `scripts={};` and compute the strings scripts["init"] etc. via javascript through a concatenation.
Or if you prefer to program javascript, you could [create a plugin](https://cindyjs.org/pub/2016-icms/plugins/#/4/3) that implements your function  `drawmystage()`.

**Comment by q2apro** [comment]
Thanks for the feedback!

From your information, then it will probably be the "multi-line cindy script solution". As I do not need to have all JS/CindyJS in **one external file** to be embedded.
