### ISSUE TITLE
Transition to ECMAscript 2016

### ISSUE THREAD

**Issue by kortenkamp** [CindyJS/CindyJS#885]
With the latest modernisations by @strobelm we should think about moving the codebase entirely to ECMAscript 2016 (ES7), as the `**` operator is ES7. 

This means - check which browsers we want/need to support and use the appropriate ECMAscript version as a target for the build process. If there is no longer a need for transpilation, I suggest to get rid of it altogether. 

Any comments?

**Comment by elkins0** [comment]
It would seem all currently supported browsers support ES7—according to [W3school's ECMAScript 2016 page](https://www.w3schools.com/js/js_2016.asp)—since:
- Jul 2016: Chrome 52 (based on Chromium)	
- Aug 2016: Edge 14 (based on Chromium)	
- Mar 2017: Firefox 52	
- Mar 2017: Safari 10.1	
- Aug 2016: Opera 39 (based on Chromium)

Full browser compatibility data is available [here](https://github.com/mdn/browser-compat-data/).
[Firefox Exponentiation documentation Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Exponentiation#browser_compatibility) displays that data for computer, mobile and server and agrees with those versions:

**Computer**
> - Chrome 52
> - Edge 14
> - Firefox 52
> - Internet Explorer (X)
> - Opera 39
> - Safari 10.1

**Mobile**
> - Chrome Android 52
> - Firefox for Android 52
> - Opera Android 41
> - Safari on iOS 10.3
> - Samsung Internet 6.0
> - WebView Android 51

**Server**
> - Deno 1.0
> - Node.js 7.0.0

According to [W3school's Internet Explorer Retirement page](https://www.w3schools.com/js/js_ie_edge.asp), Microsoft ended all support for Internet Explorer June 15, 2022.
For ES7 information see [ECMA-262 7ᵗʰ Edition / June 2016 ECMAScript® 2016 Language Specification](https://262.ecma-international.org/7.0/).

**Comment by strobelm** [comment]
I put up a merge request to move to ECMAScript 2016, this is a very safe bet right now. In the long term I would suggest that we remove the legacy build system, but this needs some larger refactoring before we can do so.

**Comment by kortenkamp** [comment]
Yes, I would love to remove the legacy build system 👍 – thank you for your help in making the move!
